### ISSUE TITLE
Wormhole doesn't delete source message when a wormhole message is

### ISSUE THREAD

**Issue by Aeris1One** [Gunivers/Gipsy#60]
1. Link two channels using wormhole
2. Send a message to one of the channels
3. Send the exact same message to another channel
4. Delete the latter one
5. The bot deletes the former while it shouldn't

https://user-images.githubusercontent.com/29739547/195160619-6b0f9a84-be8c-43a5-bd66-607ff446c308.mp4

**Comment by LeiRoF** [comment]
Won't fix.
The bug is too specific and not really possible to fix without having to create a map of message correspondance.

This bug is due to the event of message deletion which is performed on a channel and is progpagated on over the wormhole channels, where the bot will try to find the corresponding message to delete it. But as there is no possibility to pout any additional contexte (like a reason of deletion), this message deletion will trigger the wormhole deletion event, and then the bot will search all corresponding messages on connected channels (in short, as there is no correspondance map, all event on each server is seen as a source event)

This is actually not really an issue considering that this situation is absurd and cannot happen unvonluntarily.

However, another related issue that must be fixed is that, when a webhook message is deleted in a wormhole channel, it doesn't delete the user source message (only webhook messages are deleted). Fixing this issue will imply that, in the previous case, if several similar messages are sent in the same channel (and in a short period of time) and one of them get deleted, then all of them will be deleted

**Comment by Aeris1One** [comment]
> However, another related issue that must be fixed is that, when a webhook message is deleted in a wormhole channel, it doesn't delete the user source message (only webhook messages are deleted). Fixing this issue will imply that, in the previous case, if several similar messages are sent in the same channel (and in a short period of time) and one of them get deleted, then all of them will be deleted, which is a more consistent behavior.

**Comment by ascpial** [comment]
It's better to create a new issue.

**Comment by Aeris1One** [comment]
Not necessarily, this issue was a result of a bigger issue which still needs to be fixed. It seems better to edit the issue to reflect this bigger problem, instead of closing the smaller one which isn't solved

**Comment by LeiRoF** [comment]
Wrong repo
